spring:
  application:
    name: Picture_enhancement_platform
  profiles:
    active: database,paths
  servlet:
    multipart:
      max-file-size: 5MB #最大允许上传文件大小5MB
      max-request-size: 10MB #最大允许请求体中参数大小5MB
jwt:
  token:
    tokenExpiration: 604800000 #有效期7天
    tokenSignKey: SHVhbmdKdW5rYWkwMzAyMDZXaXRoSGFydXR5YTk2MTIyNg==
conda:
  env: "Real-ESRGAN "