realESRGAN:
  paths:
    outputPath: "E:/images/real-ESRGAN/ "
inputPath:  "E:/Super-Resolution_Platform/Picture_enhancement_platform/src/main/resources/images/temp/ "
inferencePythonFile:
  path: "E:/Super-Resolution_Platform/Picture_enhancement_platform/Real-ESRGAN/inference_realesrgan.py "
logging:
  file:
    path: E:\Super-Resolution_Platform\Picture_enhancement_platform\logs