spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      url: jdbc:mysql://localhost:3306/image_super_resolution
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: Flame+1226

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #日志控制台输出
  type-aliases-package: com.junkai.picture_enhancement_platform.entity